name: CI

on:
  push:
    branches: "**"
    pull_request:
env:
  FQAUTH_BUNDLE_ID: "com.fqauth.sample"
  FQAUTH_DEVELOPMENT_TEAM: "ARST1234"
  FQAUTH_SERVER_URL: https://auth.example.com
  RANDOM_STRING_SERVER_URL: https://api.example.com

jobs:
  build:
    name: Tests
    runs-on: macos-12
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - name: Xcode Setup
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "14.1"
      - run: brew bundle
      - run: swish generate
      - run: swish runtests
