name: CI

on:
  push:
    branches: "**"
    pull_request:
env:
  FQAUTH_BUNDLE_ID: "com.fqauth.sample"
  FQAUTH_DEVELOPMENT_TEAM: "ARST1234"
  FQAUTH_SERVER_URL: https://auth.example.com
  RANDOM_STRING_SERVER_URL: https://api.example.com

jobs:
  build:
    name: Tests
    runs-on: macos-12.0
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3

      - run: brew bundle
      - run: swish project
      - run: xcrun xcodebuild test -scheme App


